var rows = [
 {
  "wikidata": "Q56748073",
  "urldate": "2018-08-14",
  "url": "http://anno.onb.ac.at/cgi-content/anno?aid=wku&datum=19450901&seite=3",
  "date": "1945-09-01",
  "publisher": ['Waldheim-Eberle'],
  "location": ['Wien'],
  "pages": "3",
  "volume": "1",
  "number": "6",
  "editor": ['Oskar Maurus Fontana'],
  "journalsubtitle": "Herausgegeben von den amerikanischen Streitkräften für die Wiener Bevölkerung",
  "journaltitle": "Wiener Kurier",
  "keywords": "prose",
  "title": "Das vierte Tor",
  "author": ['Ilse Aichinger'],
  "ENTRYTYPE": "Artikel",
  "ID": "Aichinger-WienerKurier-DasvierteTor",
  "Erstpublikation": "ja",
  "genre": "prose",
  "Jahr": "1945",
  "Jahrzehnt": "1940er",
 },
 {
  "wikidata": "Q56745212",
  "date": "2016-11-16",
  "location": ['Wien'],
  "pages": "34–35",
  "number": "46/16",
  "editor": ['Armin Thurnher'],
  "journaltitle": "Falter",
  "title": "»Ich wollte immer, dass alles deutlich wird«",
  "keywords": "interview",
  "author": ['Ilse Aichinger', 'Günter Kaindlstorfer'],
  "ENTRYTYPE": "Artikel",
  "ID": "Aichinger-Interview-Falter-ichwollte",
  "Erstpublikation": "ja",
  "genre": "interview",
  "Jahr": "2016",
  "Jahrzehnt": "2010er",
 },
]